name: Build and Push Containers to GHCR

on:
  workflow_dispatch:  # Enables the "Run workflow" button in GitHub UI
  push:
    branches: [ "main" ]
    paths:
      - 'docker/**'
      - 'envs/**'
      - 'bin_python_staging/**'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        include:
          - name: cell2loc
            file: docker/cell2loc/Dockerfile
          - name: rpy2
            file: docker/rpy2/Dockerfile
          - name: r-cside
            file: docker/r-cside/Dockerfile
          - name: r-enrichment
            file: docker/r-enrichment/Dockerfile

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ matrix.file }}
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/cells2spine-${{ matrix.name }}:latest
