name: Build and Push Containers to GHCR

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - 'docker/**'
      - 'envs/**'
      - 'bin_python_staging/**'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        include:
          - name: cell2loc
            file: docker/cell2loc/cells2spine-cell2loc
          - name: rpy2
            file: docker/rpy2/cells2spine-rpy2
          - name: r-cside
            file: docker/r-cside/cells2spine-r-cside
          - name: r-enrichment
            file: docker/r-enrichment/cells2spine-r-enrichment

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Lowercase repository owner
        id: repo
        run: |
          echo "owner_lc=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ matrix.file }}
          push: true
          tags: ghcr.io/${{ steps.repo.outputs.owner_lc }}/cells2spine-${{ matrix.name }}:latest
